apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: running-it-container
  name: running-it-container
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: running-it-container
    spec:
      containers:
      - image: strm/helloworld-http
        name: running-it-container
        ports:
        - containerPort: 80
      restartPolicy: Never
