apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxy
    spec:
      containers:
      - image: galaxy/gx-it-proxy:latest
        name: proxy
        ports:
        - containerPort: 8910

