name: Publish Docker Image
on: [push]
jobs:
  build-and-publish-head:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # Running this job only for develop branch

    steps:
    - uses: actions/checkout@v2 # Checking out the repo
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: galaxyproject/gx-it-proxy/proxy
        registry: docker.pkg.github.com
        workdir: docker
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}

